<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Services\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClassicCars.Data\ClassicCars.Data.csproj" />
    <ProjectReference Include="..\ClassicCars.DataModels\ClassicCars.DataModels.csproj" />
    <ProjectReference Include="..\ClassicCars.GCommon\ClassicCars.GCommon.csproj" />
    <ProjectReference Include="..\ClassicCars.ViewModels\ClassicCars.ViewModels.csproj" />
  </ItemGroup>
</Project>
